const env={
APPWRITE_URL:String(import.meta.env.VITE_APPWRITE_URL),
APPWRITE_DB_ID:String(import.meta.env.VITE_APPWRITE_DB_ID),
APPWRITE_PROJECT_ID:String(import.meta.env.VITE_APPWRITE_PROJECT_ID),
APPWRITE_COLLECTION_ID:String(import.meta.env.VITE_APPWRITE_COLLECTION_ID),
APPWRITE_COLLECTION_CONTECT_ID:String(import.meta.env.VITE_APPWRITE_COLLECTION_CONTECT_ID),
APPWRITE_COLLECTION_PROFILE_ID:String(import.meta.env.VITE_APPWRITE_COLLECTION_PROFILE_ID),
APPWRITE_BUKET_ID:String(import.meta.env.VITE_APPWRITE_BUKET_ID),
APPWRITE_FUNCTION_AISUMMMERY:String(import.meta.env.VITE_APPWRITE_FUNCTION_AISUMMMERY),
REDIRECT_SUCCESS:String(import.meta.env.VITE_REDIRECT_SUCCESS),
REDIRECT_FAILURE:String(import.meta.env.VITE_REDIRECT_FAILURE),
REDIRECT_PASSWORD:String(import.meta.env.VITE_REDIRECT_PASSWORD),
REDIRECT_EMAIL:String(import.meta.env.VITE_REDIRECT_EMAIL),
};

export default env;