import { GoogleGenAI } from "@google/genai";

/* -------------------- Prompt Builder -------------------- */
function buildMetaDataPrompt({ title, shortDescription, keywords, content }) {
  return `
You are an AI Metadata Assistant integrated into a blogging platform.

The user is writing a blog post and wants help generating metadata.

REFERENCE INPUT (do not copy directly):
- Existing Title: "${title || ""}"
- Existing Short Description: "${shortDescription || ""}"
- Existing Keywords: ${JSON.stringify(keywords || [])}

YOUR TASK:
Analyze the blog content and generate clear, meaningful metadata
that improves content structure, readability, and preview readiness.

RESPONSE REQUIREMENTS:
Return ONLY valid JSON in the exact structure below:

{
  "title": "Metadata-optimized blog title (max 60 characters)",
  "metaDescription": "Clear and engaging description (max 160 characters)",
  "keywords": ["keyword1", "keyword2", "keyword3", "keyword4", "keyword5"],
  "aiNote": "Friendly guidance message explaining AI-generated metadata and how to apply it using the <Insert> button in the UI"
}

CRITICAL BEHAVIOR:
- If the blog content is unclear, repetitive, incomplete, or unsuitable:
  - Set title and metaDescription to empty strings
  - Set keywords to an empty array
  - Clearly explain the issue and how to fix it inside aiNote
- NEVER return partial text or anything outside JSON

CONTENT RULES:
- Do NOT copy sentences verbatim
- Do NOT invent facts or topics
- Keep language natural and human-like
- Keywords must be relevant and realistic

aiNote RULES:
- Always present
- Clearly mention content is AI-generated
- Explain how the user can apply it (Insert button or manual paste)
- Use simple, non-technical language

FORMAT RULES:
- Output JSON only
- No markdown
- No comments
- No explanations outside JSON

BLOG CONTENT:
${content}
`;
}

/* -------------------- Helpers -------------------- */

// Extract text safely from Gemini responses
function extractGeminiText(response) {
  if (response?.response?.text) {
    return response.response.text();
  }

  if (response?.candidates?.length) {
    return response.candidates[0].content.parts
      .map((p) => p.text || "")
      .join("");
  }

  return null;
}

// Remove markdown code fences if Gemini adds them
function cleanJson(text) {
  return text
    .replace(/```json/gi, "")
    .replace(/```/g, "")
    .trim();
}

/* -------------------- Main Function -------------------- */
export async function aiMetaDataGenerator({ req, res, log, error }) {
  try {
    const body =
      typeof req.body === "string" ? JSON.parse(req.body) : req.body;

    const {
      title = "",
      shortDescription = "",
      keywords = [],
      content,
    } = body;

    /* ---- Content validation ---- */
    if (!content || content.trim().length < 50) {
      return res.json({
        success: true,
        metaDataResult: {
          title: "",
          metaDescription: "",
          keywords: [],
          aiNote:
            "AI could not generate metadata because the content is too short. Please add more meaningful text (at least one paragraph) and try again.",
        },
      });
    }

    const ai = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY,
    });

    const prompt = buildMetaDataPrompt({
      title,
      shortDescription,
      keywords,
      content,
    });

    const response = await ai.models.generateContent({
      model: process.env.LLM_MODEL,
      contents: prompt,
      config: {
        response_mime_type: "application/json",
      },
    });

    const rawText = extractGeminiText(response);
    if (!rawText) throw new Error("Empty AI response");

    const cleanedText = cleanJson(rawText);
    log("AI RAW RESPONSE:", cleanedText);

    let metaDataResult;
    try {
      metaDataResult = JSON.parse(cleanedText);
    } catch {
      throw new Error("AI returned invalid JSON");
    }

    /* ---- Final safety net ---- */
    if (!metaDataResult.aiNote) {
      metaDataResult.aiNote =
        "This metadata was generated by AI. You can insert it using the Insert button or manually edit it before publishing.";
    }

    return res.json({
      success: true,
      metaDataResult,
    });
  } catch (err) {
    error("AI Metadata Generator Error: " + err.message);
    return res.json(
      {
        success: false,
        error: err.message,
      },
      500
    );
  }
}
