import { GoogleGenAI } from "@google/genai";

/* -------------------- Prompt Builder -------------------- */
function buildSeoPrompt({ title, shortDescription, keywords, content }) {
  return `
You are an AI SEO assistant integrated into a blogging platform.

The user is writing a blog post and wants SEO suggestions.

REFERENCE INPUT (do not copy directly):
- Existing Title: "${title || ""}"
- Existing Short Description: "${shortDescription || ""}"
- Existing Keywords: ${JSON.stringify(keywords || [])}

YOUR TASK:
Carefully analyze the blog content and generate SEO metadata that improves
search visibility while preserving the original meaning.

RESPONSE REQUIREMENTS:
Return ONLY valid JSON in the exact structure below:

{
  "title": "SEO-friendly blog title (max 60 characters)",
  "metaDescription": "Clear, engaging meta description (max 160 characters)",
  "keywords": ["keyword1", "keyword2", "keyword3", "keyword4", "keyword5"],
  "aiNote": "Friendly guidance message for the user"
}

CRITICAL BEHAVIOR:
- If the blog content is unclear, repetitive, incomplete, or unsuitable for SEO:
  - Set title and metaDescription to empty strings
  - Set keywords to an empty array
  - Clearly explain the problem and how to fix it inside aiNote
- NEVER fail or return partial text outside JSON

CONTENT RULES:
- Do NOT copy sentences verbatim from the blog
- Do NOT invent new facts or topics
- Keep language natural and human-like
- Keywords must be relevant and realistic (no stuffing)

aiNote RULES:
- Always present
- Clearly mention the content is generated by AI
- Explain how the user can apply it (Insert button or manual paste)
- If there is a problem, explain it in simple, non-technical language

FORMAT RULES:
- Output JSON only
- No markdown
- No comments
- No explanations outside JSON

BLOG CONTENT:
${content}
`;
}


/* -------------------- Helpers -------------------- */

// Extract text safely from Gemini responses
function extractGeminiText(response) {
  if (response?.response?.text) {
    return response.response.text();
  }

  if (response?.candidates?.length) {
    return response.candidates[0].content.parts
      .map((p) => p.text || "")
      .join("");
  }

  return null;
}

// Remove markdown code fences if Gemini adds them
function cleanJson(text) {
  return text
    .replace(/```json/gi, "")
    .replace(/```/g, "")
    .trim();
}

/* -------------------- Main Function -------------------- */
export async function seoEnhancer({ req, res, log, error }) {
  try {
    const body =
      typeof req.body === "string" ? JSON.parse(req.body) : req.body;

    const {
      title = "",
      shortDescription = "",
      keywords = [],
      content,
    } = body;

    /* ---- Content validation (AI-friendly) ---- */
    if (!content || content.trim().length < 50) {
      return res.json({
        success: true,
        seoResult: {
          title: "",
          metaDescription: "",
          keywords: [],
          aiNote:
            "AI could not generate SEO data because the blog content is too short. Please add more meaningful text (at least one full paragraph) and try again.",
        },
      });
    }

    const ai = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY,
    });

    const prompt = buildSeoPrompt({
      title,
      shortDescription,
      keywords,
      content,
    });

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        response_mime_type: "application/json",
      },
    });

    const rawText = extractGeminiText(response);
    if (!rawText) throw new Error("Empty AI response");

    const cleanedText = cleanJson(rawText);
    log("AI RAW RESPONSE:", cleanedText);

    let seoResult;
    try {
      seoResult = JSON.parse(cleanedText);
    } catch {
      throw new Error("AI returned invalid JSON");
    }

    /* ---- Final safety net ---- */
    if (!seoResult.aiNote) {
      seoResult.aiNote =
        "This SEO content was generated by AI. You can insert it into your post using the Insert button or manually edit it before publishing.";
    }

    return res.json({
      success: true,
      seoResult,
    });
  } catch (err) {
    error("SEO Enhancer Error: " + err.message);
    return res.json(
      {
        success: false,
        error: err.message,
      },
      500
    );
  }
}
